### PR TITLE
[Samples][11.qnamaker] Add README

### PR DESCRIPTION
**Pull request by Batta32**
Fixes #

## Specific Changes

  - 
  -
  -

### CODE REVIEW

**Review by FedericoBernal — APPROVED** [review]
The sentence "An account on Azure if you want to deploy to Azure." inside the prerequisites sounds redundant, apart from that LGTM

**Comment by Batta32** [comment]
Agree with you, but it's completely a copy paste from C# :sad-pepe:

**Comment by FedericoBernal** [comment]
> Agree with you, but it's completely a copy paste from C# :sad-pepe:

I'm not seeing that line in [C# README](https://github.com/microsoft/BotBuilder-Samples/blob/main/samples/csharp_dotnetcore/11.qnamaker/README.md). I thought you added that line, that's why I commented that 🤔

**Comment by Batta32** [comment]
My bad, that part is a copy paste from the READMEs of the Java's samples

**Pull request merged**
