### PR TITLE
[17.multilingual-bot] Update application.java

### PR DESCRIPTION
**Pull request by VictorGrycuk**
Fixes #

## Specific Changes

  - 
  -
  -

### CODE REVIEW

**Review by Batta32 — CHANGES_REQUESTED** [review]
* Should we add the `@Bin` annotation?
* Also, with your changes the `getBotFrameworkHttpAdaptor` can be improved

**Comment by fran893** [comment]
The configuration you added, shouldn't be added in the [BotDependencyConfiguration](https://github.com/southworks/botbuilder-java/blob/main/libraries/bot-integration-spring/src/main/java/com/microsoft/bot/integration/spring/BotDependencyConfiguration.java) and then, call them from the `getBotFrameworkHttpAdaptor`?

**Comment by VictorGrycuk** [comment]
> 
> 
> The configuration you added, shouldn't be added in the [BotDependencyConfiguration](https://github.com/southworks/botbuilder-java/blob/main/libraries/bot-integration-spring/src/main/java/com/microsoft/bot/integration/spring/BotDependencyConfiguration.java) and then, call them from the `getBotFrameworkHttpAdaptor`?

About this, not sure, several samples add the methods themselves, as sample 16, or sample 47

**Review by Batta32 — CHANGES_REQUESTED** [review]
See `getBotFrameworkHttpAdaptor`, we can remove the line 54, 55

After this LGTM

**Review by Batta32 — APPROVED** [review]
LGTM

**Review by fran893 — APPROVED** [review]

**Pull request merged**
