### PR TITLE
[SDK][Bot-Azure] Add CosmosDbPartitionedStorage component

### PR DESCRIPTION
**Pull request by VictorGrycuk**
Fixes #

## Description

Implements support for `CosmosDbPartitionedStorage` class and its tests.

## Specific Changes

Adds the following classes:
  - `CosmosDbPartitionedStorage`
  - `CosmosDbPartitionedStorageOptions`
  - `CosmosDbKeyEscape`
  - Updates the `pom.xml` file with the necessary dependencies
  - Adds the necessary tests for the `CosmosDbPartitionedStorage` and `CosmosDbKeyEscape` classes

## Testing

_Unit tests of bot-azure passing correctly_
image

_mvn clean install passing correctly_
image

### CODE REVIEW

**Review by Batta32 — CHANGES_REQUESTED** [review]
I see files like:
- `libraries/bot-azure/DocumentDB.Spatial.Sql.dll`
- `libraries/bot-azure/Microsoft.Azure.Documents.ServiceInterop.dll`

is it okay?

Also, just for parity with other tests in Java, can we rename all the unit tests to be `lowerCamelCase`?

**Comment by VictorGrycuk** [comment]
@Batta32 Those files were added by Tracy in his initial commit.
I will update the tests names.

**Review by Batta32 — CHANGES_REQUESTED** [review]
Remove the `.dlls`, I didn't find those in C# and I think that we can receive feedback from Tracy because of this.

After removing, execute the unit tests + `mvn clean install` to confirm that eveything is working

**Comment by Batta32** [comment]
Don't forget to prepare a comment in the PR telling about the necessary changes in build to have these tests passing

**Review by Batta32 — APPROVED** [review]

**Comment by Batta32** [comment]
Merged in MS

**Pull request closed without merging**
